new_topic_button_icon:
  default: "plus"
show_button_text:
  default: true
new_topic_button_text:
  default: ""
new_topic_button_title:
  default: ""
hide_default_button:
  default: true
show_to_anon:
  default: false
